### ISSUE TITLE
Feedback on the fantastic new free.law redesign

### ISSUE THREAD

**Issue by flooie** [freelawproject/free.law#51] opened 2021-08-05 14:35 UTC
In an attempt to organize my (and other) feedback on the new free.law website redesign.  

Overall, its a huge improvement, and I only have a few nit-picky details to add.

**Comment by flooie** [comment] 2021-08-05 14:36
On Safari Version 14.1.1 (16611.2.7.1.4)

<img width="154" alt="Screen Shot 2021-08-05 at 10 29 15 AM" src="https://user-images.githubusercontent.com/6464529/128368486-0005b3f2-f740-4bb2-a486-03319081f349.png">
<img width="59" alt="Screen Shot 2021-08-05 at 10 29 23 AM" src="https://user-images.githubusercontent.com/6464529/128368489-3a451744-aa9a-41c4-9638-a95c77724908.png">

When selecting the dropdown menus - the border overalls with the text.

**Comment by flooie** [comment] 2021-08-05 14:38
On Safari Mobile Beta 15-- ![IMG_0959](https://user-images.githubusercontent.com/6464529/128368703-f876845e-63e6-481e-bcea-10537a9e2661.jpeg)

The button Learn More about our Data Services is too close to the logos.  The spacing is inconsistent compared to other sections with the buttons.

**Comment by flooie** [comment] 2021-08-05 14:41
The same issue occurs on Safari Desktop at both 3 and four column spacing.


<img width="1453" alt="Screen Shot 2021-08-05 at 10 29 01 AM" src="https://user-images.githubusercontent.com/6464529/128369145-531b537c-0fdd-4d62-9f99-86f93bc0ad53.png">
<img width="672" alt="Screen Shot 2021-08-05 at 10 39 26 AM" src="https://user-images.githubusercontent.com/6464529/128369149-9c64f40a-65e2-42d3-905b-6cf58b1ff64d.png">


Also - I think it would look nicer to just default to three columns everytime in desktop with the current number of logos.

**Comment by flooie** [comment] 2021-08-05 14:44
Two things, both minor.  

I think we C is being cut off slightly in this image.  

And I think we need a higher resolution logo?

<img width="849" alt="Screen Shot 2021-08-05 at 10 43 01 AM" src="https://user-images.githubusercontent.com/6464529/128369633-2b0ec9b3-0a62-4648-bc50-0866a069b998.png">

**Comment by flooie** [comment] 2021-08-05 14:53
This is almost certainly just me - but is anyone else bothered that the angle for these three similar icons are slightly different.  

The first being much more skewed than the second and third.  I added the red line to help illustrate my thoughts.  

<img width="1228" alt="Screen Shot 2021-08-05 at 10 48 05 AM" src="https://user-images.githubusercontent.com/6464529/128371078-a9b4e645-55b5-4c98-b83e-5379e3553e88.png">

**Comment by flooie** [comment] 2021-08-05 14:58
Back to low resolution logos - this time in the dropdown again bothers me.


<img width="167" alt="Screen Shot 2021-08-05 at 10 55 20 AM" src="https://user-images.githubusercontent.com/6464529/128371897-201af9b7-6269-4084-8cce-828643d96617.png">


Also -  I understand why RECAP and CL have colorful icons, but why does data services also get one - while everything else is basically grayscale?


<img width="285" alt="Screen Shot 2021-08-05 at 10 55 44 AM" src="https://user-images.githubusercontent.com/6464529/128371949-1bc766ff-17a2-4854-a48d-ac17f817b7d5.png">

**Comment by mlissner** [comment] 2021-08-05 20:30
OK:

 - The outline overlap is fixed.
 - The spacing on the button is fixed
 - The low resolution stuff is weird. These are SVGs. There's one post on stackoverflow that says you have to make the SVG larger, then scale it down by half using CSS, and, well, I guess I can't be bothered.
 - I made the icon grayscale
 - Rotating the books logo seems hard. We have the original SVG though, if anybody is up for it. I think you're right, but I don't think I'll tinker with it.
 - I couldn't reproduce the cut-off C thing

No typos so far, beyond those my mom found. That's good.

**Comment by flooie** [comment] 2021-08-05 20:45
Lots of Oxford commas though.  

Last tidbits.

About is higher than projects.

<img width="531" alt="Screen Shot 2021-08-05 at 4 39 46 PM" src="https://user-images.githubusercontent.com/6464529/128418572-043f6f06-8221-4e38-83c1-6504322bae6a.png">


Projects isn't really centered.
<img width="351" alt="Screen Shot 2021-08-05 at 4 39 58 PM" src="https://user-images.githubusercontent.com/6464529/128418626-f66f0040-3d77-4c3b-9e2e-829ca9bc1d79.png">

**Comment by mlissner** [comment] 2021-08-05 23:03
I like oxford commas. 

Getting that ABOUT to be down half a pixel was terrible, but it bugged me too. I was hoping nobody would notice. 

I don't care about the outline on Projects. :)

**Comment by mattdahl** [comment] 2021-08-07 18:17
The "C" in the CL logo looks cut off to me too, on the latest versions of Firefox and Safari for macOS. The file itself looks cut off to me on the left here: https://free.law/images/homepage/courtlistener-stacked.svg

**Comment by mlissner** [comment] 2021-08-08 15:17
Boo. They're fine here, even going straight to that link. I guess we better use pngs. Lame.

**Comment by mlissner** [comment] 2021-08-10 22:35
OK, I can't prove it, but I think I fixed the cut off logo issue. Can somebody verify that the C looks better? I'm using a PNG now instead of an SVG.

**Comment by mattdahl** [comment] 2021-08-12 05:47
It's fixed for me!

**Comment by mlissner** [comment] 2021-08-12 05:53
I think we're done here. Closing, but y'all know where to find me if I'm premature on this one.

**Comment by mlissner** [comment] 2021-08-12 05:53
And thank you both!

**Closed by mlissner** 2021-08-12 05:53 UTC
